sudo: false
script:
- make install && make test && make provision
- make tidy
language: node_js
node_js:
- '0.12.2'
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make deploy
